### ISSUE TITLE
Handle text overflow and user preference text size gracefully

### ISSUE THREAD

**Issue by kirahsapong** [TBD54566975/didpay#41] opened 2024-02-01 18:14 UTC
Text overflows on devices with text size enlarged. Large numbers also fall off the edge. 

![Simulator Screenshot - iPhone 15 - 2024-02-01 at 10 13 01](https://github.com/TBD54566975/didpay/assets/102400653/a6059e4d-8a54-4af9-b455-0690cf5ba2e2)
![Simulator Screenshot - iPhone 15 - 2024-02-01 at 10 13 14](https://github.com/TBD54566975/didpay/assets/102400653/8a82d84c-8ee9-44cc-b868-a27b438b7d4a)

**Comment by ethan-tbd** [comment] 2024-04-12 21:04
overflow caused by large numbers has been fixed by the use of [AutoSizeText](https://pub.dev/packages/auto_size_text)

**Closed by ethan-tbd** 2024-04-12 21:04 UTC
Labels: bug
